GET http://localhost:9200/movies/_search?pretty
Content-Type: application/json

{
    "query": {
        "match": {
            "title": "Star Trek"
        }
    }
}
###

GET http://localhost:9200/movies/_search?pretty
Content-Type: application/json

{
    "query": {
        "match_phrase": {
            "genre": "sci"
        }
    }
}
###

DELETE http://localhost:9200/movies
###


PUT http://localhost:9200/movies
Content-Type: application/json

{
    "mappings": {
        "properties": {
            "id": {
                "type": "integer"
            },
            "year": {
                "type": "date"
            },
            "genre": {
                "type": "keyword"
            },
            "title": {
                "type": "text",
                "analyzer": "english"
            }
        }
    }
}
###

PUT http://localhost:9200/_bulk?pretty
Content-Type: application/json

< ./json_files/movies.json
###

GET http://localhost:9200/movies/_search?pretty
Content-Type: application/json

{
    "query": {
        "match_phrase": {
            "genre": "Sci-Fi"
        }
    }
}
###

GET http://localhost:9200/movies/_search?pretty
Content-Type: application/json

{
    "query": {
        "match": {
            "title": "Star Trek"
        }
    }
}
###